======================================================================
ERROR: test_style_test (test_code_style.TestCodeStyle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_module\test_code_style.py", line 79, in test_style_test
    "Unable to import 'keyring'",
  File "C:\xavierdupre\__home_\GitHub\pyquickhelper\src\pyquickhelper\pycode\utils_tests_helper.py", line 418, in check_pep8
    "{0} lines\n{1}".format(len(lines), "\n".join(lines)))
pyquickhelper.pycode.utils_tests_helper.PEP8Exception: 8 lines
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:72: E0611: No name 'jupytalk' in module 'src' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:72: E0401: Unable to import 'src.jupytalk.mokadi' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:73: E0611: No name 'jupytalk' in module 'src' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:73: E0401: Unable to import 'src.jupytalk.mokadi.grammars' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:93: E0611: No name 'jupytalk' in module 'src' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:93: E0401: Unable to import 'src.jupytalk.mokadi' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:94: E0611: No name 'jupytalk' in module 'src' (pylint)
C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py:94: E0401: Unable to import 'src.jupytalk.mokadi.grammars' (pylint)

----------------------------------------------------------------------
Ran 3 tests in 58.256s

FAILED (errors=1)
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
======================================================================
ERROR: test_mokadi_interpret (test_grammar_mokadi.TestGrammarMokadi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py", line 72, in test_mokadi_interpret
    from src.jupytalk.mokadi import interpret
ModuleNotFoundError: No module named 'src.jupytalk'

======================================================================
ERROR: test_mokadi_interpret_exception (test_grammar_mokadi.TestGrammarMokadi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_grammar_mokadi.py", line 93, in test_mokadi_interpret_exception
    from src.jupytalk.mokadi import interpret
ModuleNotFoundError: No module named 'src.jupytalk'

----------------------------------------------------------------------
Ran 3 tests in 0.068s

FAILED (errors=2)
----------------------------------------------------------------------
Ran 1 test in 0.278s

OK
----------------------------------------------------------------------
Ran 1 test in 1.474s

OK
----------------------------------------------------------------------
Ran 1 test in 1.619s

OK
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
----------------------------------------------------------------------
Ran 2 tests in 0.031s

OK
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
----------------------------------------------------------------------
Ran 1 test in 2.195s

OK
----------------------------------------------------------------------
Ran 1 test in 0.018s

OK
======================================================================
ERROR: test_mail (test_mail.TestMail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\src\botadi\mokadi\mokadi_mails.py", line 33, in enumerate_last_mails
    box.login()
  File "C:\xavierdupre\__home_\GitHub\pymmails\src\pymmails\grabber\mailboximap.py", line 60, in login
    self.M.login(self._user, self._password)
  File "c:\Python370_x64\lib\imaplib.py", line 591, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "c:\Python370_x64\lib\imaplib.py", line 1183, in _quote
    arg = arg.replace('\\', '\\\\')
AttributeError: 'NoneType' object has no attribute 'replace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_mail.py", line 50, in test_mail
    for mail in mails:
  File "C:\xavierdupre\__home_\GitHub\botadi\src\botadi\mokadi\mokadi_mails.py", line 35, in enumerate_last_mails
    raise MokadiAuthentification("Unable to connect to the mailbox") from e
src.botadi.mokadi.mokadi_exceptions.MokadiAuthentification: Unable to connect to the mailbox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_mail.py", line 57, in test_mail
    raise Exception("Does not work") from e
Exception: Does not work

----------------------------------------------------------------------
Ran 1 test in 0.796s

FAILED (errors=1)
